format: table
exit-code: 1
severity:
  - HIGH
  - CRITICAL
ignorefile: .trivyignore
scan:
  skip-dirs:
    - files
    - node_modules
    - vendor
    - dist
    - build
    - .vscode
    - .idea
    - .DS_Store
  skip-files:
    - .devcontainer/.env.secret
