ARG GO_VERSION=1.25

FROM mcr.microsoft.com/devcontainers/go:2-${GO_VERSION}-bookworm


RUN curl -sS https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    bash-completion uuid-runtime iputils-ping zsh postgresql-client \
    trivy apt-transport-https gnupg lsb-release \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

USER vscode

RUN go install -v github.com/cweill/gotests/gotests@v1.6.0 && \
    go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.2.1 && \
    # go install -v github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1 && \
    # go install -v github.com/KarnerTh/mermerd@latest && \
    go install golang.org/x/vuln/cmd/govulncheck@latest && \
    go install mvdan.cc/gofumpt@latest

WORKDIR /workspace